- id: cmake-lint
  name: CMake Linter (ast-grep)
  entry: cmake-scan
  #TODO: recommend in README to disable color because it leaves behind ANSI code fragments
  language: node
  require_serial: true
  additional_dependencies:
    - "@ast-grep/cli"
    - "yaml"
  types:
    - cmake
