ruleDirs:
  - rules
testConfigs:
  - testDir: rules-test
utilDirs:
  - utils
languageGlobs:
  cmake:
    - "*.cmake"
    - "**/CMakeLists.txt"
customLanguages:
  cmake:
    libraryPath: cmake.so
    extensions:
      - cmake
